# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - hand_controller
    - panda_arm_controller

  hand_controller:
    type: GripperCommand
    joints:
      - fer_finger_joint1
    action_ns: gripper_cmd
    default: true
  panda_arm_controller:
    type: FollowJointTrajectory
    joints:
      - fer_joint1
      - fer_joint2
      - fer_joint3
      - fer_joint4
      - fer_joint5
      - fer_joint6
      - fer_joint7
    action_ns: follow_joint_trajectory
    default: true